DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS checkin;
DROP TABLE IF EXISTS checkout;

-- 用户表
CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

-- 客户表
CREATE TABLE customer (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  address TEXT NOT NULL
);

-- 房间表
CREATE TABLE room (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  wind_speed INTEGER NOT NULL,
  mode TEXT NOT NULL
);

-- 入住表
CREATE TABLE checkin (
  customer_id INTEGER NOT NULL,
  room_id INTEGER NOT NULL,
  date DATETIME NOT NULL
);

-- 退房表
CREATE TABLE checkout (
  customer_id INTEGER NOT NULL,
  room_id INTEGER NOT NULL,
  date DATETIME NOT NULL
);
